on:
  push:
    branches:
      - main
jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Puppeteer Screenshot Action
        uses: lannonbr/puppeteer-screenshot-action@1.3.1
        with:
          url: https://github.com
