on:
  push:
    branches:
      - main
jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Generate performance reports
        uses: "lannonbr/puppeteer-screenshot-action@latest"
        with:
          url: https://github.com
